DEFAULT:
  perform_check: no

esp_pylib:
  perform_check: yes
  include:
    - 'esp_pylib/'
  allowed_licenses:
    - Apache-2.0
  license_for_new_files: Apache-2.0
  new_notice_python: |
    # SPDX-FileCopyrightText: {years} Espressif Systems (Shanghai) CO LTD
    # SPDX-License-Identifier: {license}
  espressif_copyright: '{years} Espressif Systems (Shanghai) CO LTD'
